### PR TITLE
Injection format change

### PR DESCRIPTION
**Pull request by brettahale**
Can use grunt uglify with these changes

### CODE REVIEW

**Comment by cgarvis** [comment]
Wny not use the minified version already prepared for you?

**Comment by brettahale** [comment]
We're using a build script with grunt js and are concating and minimizing many files. Some libraries do not have minimized versions so it's easier to treat them all the same way and use uglify through grunt in one shot. No biggie if you don't want to do it but figured it'd be ok this way too.

**Comment by cstephe** [comment]
I agree with brett,  that is how i normally expect it as well.

**Comment by voor** [comment]
:+1:

**Pull request merged**
